[colors.primary]
background = "#%%background%%"
foreground = "#%%foreground%%"

[colors.cursor]
text = "#%%background%%"
cursor = "#%%foreground%%"

[colors.normal]
black   = "#%%color0.hex%%"
red     = "#%%color1.hex%%"
green   = "#%%color2.hex%%"
yellow  = "#%%color3.hex%%"
blue    = "#%%color4.hex%%"
magenta = "#%%color5.hex%%"
cyan    = "#%%color6.hex%%"
white   = "#%%color7.hex%%"

[colors.bright]
black   = "#%%color8.hex%%"
red     = "#%%color9.hex%%"
green   = "#%%color10.hex%%"
yellow  = "#%%color11.hex%%"
blue    = "#%%color12.hex%%"
magenta = "#%%color13.hex%%"
cyan    = "#%%color14.hex%%"
white   = "#%%color15.hex%%"

